"""zero ads guard

Revision ID: 049fd935ca73
Revises: 3b71e9f0a4cd
Create Date: 2026-05-15 07:10:19.839387

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "049fd935ca73"
down_revision = "3b71e9f0a4cd"
branch_labels = None
depends_on = None


def upgrade():
    # NOT NULL booleans need a server_default so existing rows backfill
    # cleanly — alembic autogen leaves that off; without it the migration
    # fails on any deployment that already has output_settings /
    # processing_job rows. False is the safe default for all three flags.
    with op.batch_alter_table("output_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_retry_zero_ads_on_parse_error",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ad_windows_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "had_classification_parse_error",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "auto_retry_attempted",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.drop_column("auto_retry_attempted")
        batch_op.drop_column("had_classification_parse_error")
        batch_op.drop_column("ad_windows_count")

    with op.batch_alter_table("output_settings", schema=None) as batch_op:
        batch_op.drop_column("auto_retry_zero_ads_on_parse_error")

    # ### end Alembic commands ###
