"""add notification settings

Revision ID: 080b5181e23a
Revises: 88710a0fe69c
Create Date: 2026-07-07 22:46:35.558569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080b5181e23a'
down_revision = '88710a0fe69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('apprise_urls', sa.Text(), nullable=True),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=False),
    sa.Column('notify_on_success', sa.Boolean(), nullable=False),
    sa.Column('notify_on_rust_fallback', sa.Boolean(), nullable=False),
    sa.Column('include_llm_explanation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
