"""add bleep padding output settings

Revision ID: 0cd8f1e2d228
Revises: 60be2d5ed91b
Create Date: 2026-05-04 20:07:33.884425

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0cd8f1e2d228"
down_revision = "60be2d5ed91b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "bleep_padding_start_ms",
                sa.Integer(),
                nullable=False,
                server_default="150",
            )
        )
        batch_op.add_column(
            sa.Column(
                "bleep_padding_end_ms",
                sa.Integer(),
                nullable=False,
                server_default="150",
            )
        )

    with op.batch_alter_table("whisper_settings", schema=None) as batch_op:
        batch_op.drop_column("local_model")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("whisper_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "local_model",
                sa.TEXT(),
                server_default=sa.text("'base.en'"),
                nullable=False,
            )
        )

    with op.batch_alter_table("output_settings", schema=None) as batch_op:
        batch_op.drop_column("bleep_padding_end_ms")
        batch_op.drop_column("bleep_padding_start_ms")

    # ### end Alembic commands ###
