"""add bleep post windows

Revision ID: 157353025392
Revises: e861ad991126
Create Date: 2026-04-08 21:59:01.721819

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "157353025392"
down_revision = "e861ad991126"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bleep_windows", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("bleep_windows")

    # ### end Alembic commands ###
