"""add remote whisper diarization settings

Revision ID: 1b134819b10d
Revises: 3e5eebc6b3b1
Create Date: 2026-04-04 21:52:46.161942

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b134819b10d"
down_revision = "3e5eebc6b3b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("whisper_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "remote_diarize",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "remote_speaker_embeddings",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("whisper_settings", schema=None) as batch_op:
        batch_op.drop_column("remote_speaker_embeddings")
        batch_op.drop_column("remote_diarize")

    # ### end Alembic commands ###
