"""add audio segments for ina diarization

Revision ID: 60be2d5ed91b
Revises: deb961bb5d07
Create Date: 2026-04-18 20:24:52.596789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60be2d5ed91b'
down_revision = 'deb961bb5d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('model_call_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_call_id'], ['model_call.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_segment', schema=None) as batch_op:
        batch_op.create_index('ix_audio_segment_post_id_start_time', ['post_id', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_segment', schema=None) as batch_op:
        batch_op.drop_index('ix_audio_segment_post_id_start_time')

    op.drop_table('audio_segment')
    # ### end Alembic commands ###
