"""add speaker logs

Revision ID: 822636f3cb8d
Revises: 1b134819b10d
Create Date: 2026-04-04 23:01:28.362721

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "822636f3cb8d"
down_revision = "1b134819b10d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcript_segment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("speaker_label", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcript_segment", schema=None) as batch_op:
        batch_op.drop_column("speaker_label")

    # ### end Alembic commands ###
