"""add next_retry_at and chapter_full_block_text settings

Revision ID: 88710a0fe69c
Revises: a5e9a6d6d505
Create Date: 2026-06-10 11:16:16.733601

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88710a0fe69c"
down_revision = "a5e9a6d6d505"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("chapter_full_block_text", sa.Boolean(), nullable=True)
        )

    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        # server_default backfills the existing singleton row; SQLite cannot
        # add a NOT NULL column without one (same adjustment as the
        # enable_boundary_refinement migration, f7a4195e0953).
        batch_op.add_column(
            sa.Column(
                "chapter_full_block_text",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.add_column(sa.Column("next_retry_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.drop_column("next_retry_at")

    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("chapter_full_block_text")

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("chapter_full_block_text")

    # ### end Alembic commands ###
