"""add whisper and ina cost rates

Revision ID: 9f14d34e725a
Revises: d9eae6660c23
Create Date: 2026-05-27 21:49:58.438945

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f14d34e725a"
down_revision = "d9eae6660c23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "whisper_cost_rate_per_hour",
                sa.Float(),
                nullable=False,
                server_default="0.04",
            )
        )
        batch_op.add_column(
            sa.Column(
                "ina_cost_rate_per_hour",
                sa.Float(),
                nullable=False,
                server_default="0.0",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("ina_cost_rate_per_hour")
        batch_op.drop_column("whisper_cost_rate_per_hour")

    # ### end Alembic commands ###
