"""add estimated_cost_usd to model_call

Revision ID: a5e9a6d6d505
Revises: 9f14d34e725a
Create Date: 2026-05-28 21:33:08.605548

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5e9a6d6d505"
down_revision = "9f14d34e725a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.add_column(sa.Column("estimated_cost_usd", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.drop_column("estimated_cost_usd")

    # ### end Alembic commands ###
