"""add service_tier to ModelCall

Revision ID: b057c40113fd
Revises: b2ac822fabd0
Create Date: 2026-05-26 13:34:22.309705

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b057c40113fd"
down_revision = "b2ac822fabd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.add_column(sa.Column("service_tier", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.drop_column("service_tier")

    # ### end Alembic commands ###
