"""add llm_service_tier to LLMSettings

Revision ID: b2ac822fabd0
Revises: 049fd935ca73
Create Date: 2026-05-26 09:09:48.318694

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b2ac822fabd0"
down_revision = "049fd935ca73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "llm_service_tier",
                sa.Text(),
                nullable=False,
                server_default="default",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("llm_service_tier")

    # ### end Alembic commands ###
