"""add token usage to model_call

Revision ID: d718b3d6279f
Revises: b057c40113fd
Create Date: 2026-05-27 21:08:24.708242

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d718b3d6279f"
down_revision = "b057c40113fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompt_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("completion_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("total_tokens", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.drop_column("total_tokens")
        batch_op.drop_column("completion_tokens")
        batch_op.drop_column("prompt_tokens")

    # ### end Alembic commands ###
