"""add cached prompt tokens to model call

Revision ID: d9eae6660c23
Revises: d718b3d6279f
Create Date: 2026-05-27 21:34:58.698378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9eae6660c23'
down_revision = 'd718b3d6279f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_prompt_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_call', schema=None) as batch_op:
        batch_op.drop_column('cached_prompt_tokens')

    # ### end Alembic commands ###
