"""add transcript word timestamps cache

Revision ID: deb961bb5d07
Revises: 157353025392
Create Date: 2026-04-11 17:25:27.149899

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "deb961bb5d07"
down_revision = "157353025392"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("transcript_word_timestamps", sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("transcript_word_timestamps")

    # ### end Alembic commands ###
