"""add profanity bleeping feed settings

Revision ID: e861ad991126
Revises: 822636f3cb8d
Create Date: 2026-04-08 21:30:16.187407

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e861ad991126"
down_revision = "822636f3cb8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_profanity_bleeping",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "confirm_whisperx_endpoint",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("confirm_whisperx_endpoint")
        batch_op.drop_column("enable_profanity_bleeping")

    # ### end Alembic commands ###
