name: Python Linting, Formatting, and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Python
        id: python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"

      - name: Install ffmpeg
        run: sudo apt-get update -y && sudo apt-get install -y --no-install-recommends ffmpeg

      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Run ty check
        run: uv run ty check

      - name: Run ruff check
        run: uv run ruff check src

      - name: Run ruff format
        run: uv run ruff format --check src

      - name: Run pytest
        run: uv run pytest --disable-warnings
